server:
  port: 9000


eureka:
  instance:
    hostname: localhost # 主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: config-consumer
  rabbitmq:
    host: 117.50.163.15
    port: 5672
    virtual-host: /
    username: admin
    password: admin

# 开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true